### ISSUE TITLE
Addon is incompatible with multiprocess

### ISSUE THREAD

**Issue by HeikoAdams** [palant/enforceencryption#10]
The addon compabilitiy reporter claims enforce encryption addon as incompatible with multiprocess (e10s).

**Comment by palant** [comment]
The addon compatibility reporter is wrong, and I just verified once again that it is working just fine. However, the latest release isn't marked as "fully E10S compatible" yet, it simply wasn't worth doing a new release. But I guess that getting bug reports like this one is reason enough, I'll release version 1.0.6...
