### ISSUE TITLE
Check box missing with Firefox 43

### ISSUE THREAD

**Issue by jomo** [palant/enforceencryption#5]
Although you have marked the plugin as compatible in 2403855d2818860c55817c07722c09f60d9d141f, the check box in the `Page Info` window seems to be missing:

![screenshot](https://i.imgur.com/WxkIqKu.png)

Unfortunately the missing check box renders the plugin quite useless :cry: 

In fact, I think it has been missing in prior versions of FF as well.
I installed `Version 1.0.2.1-signed` [via addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/enforce-encryption/).

**Comment by palant** [comment]
Thank you for reporting this, fixed. I'll upload a new release to AMO soon.

**Comment by jomo** [comment]
Thanks for the ultra fast response & fix! :smiley:
