### ISSUE TITLE
Don't allow sites to remove HSTS

### ISSUE THREAD

**Issue by jomo** [palant/enforceencryption#6]
Some sites set stupid headers such as
```HTTP
Strict-Transport-Security: max-age=1
```

CloudFlare even allows you to set it to 0 seconds:

![cloudflare screenshot](https://i.imgur.com/FozWIKT.png)

i.e. HSTS is valid for only 0 or 1 seconds.

So this is what happens:

0. You visit a site via HTTPS
0. You toggle encryption using this plugin
0. You visit the site again via HTTP
  - It automatically switches to HTTPS
  - It also sets the `max-age` to 1 second
0. You visit the site once again via HTTP
  - HSTS is disabled because it expired
  - It does not default to HTTPS

**Comment by palant** [comment]
I think fixing misconfigured websites is out of scope for this extension - it's meant for websites that support HTTPS throughout the entire website but didn't yet configure HSTS for some reason (like Google). You should really report issues with the HSTS header to the owner of the website. If they are incapable of fixing it then chances are that the issues with this website cannot be alleviated by merely switching to HTTPS.

**Comment by jomo** [comment]
Hmm yeah, you're right.
Perhaps you could add to the plugin description that sites can not only enable HSTS when you disabled it, but that the opposite applies as well?

It took me a while to figure this out and it wasn't immediately obvious. Less experienced users will probably just assume the plugin is not working properly.

**Comment by palant** [comment]
True, I've added a sentence on that.

**Comment by jomo** [comment]
:+1:
