### ISSUE TITLE
wishlist: HSTS manager

### ISSUE THREAD

**Issue by ck-on** [palant/enforceencryption#8]
Thanks for making this, the only other extension for firefox that did this, Force TLS, stopped working:
https://addons.mozilla.org/en-US/firefox/addon/force-tls/

What I miss from the other extension however is it had a HSTS manager that could list all the HSTS forced sites and directly add from there, with wildcards optional, etc. like you can see in the screenshot:

![127336](https://cloud.githubusercontent.com/assets/3338142/10794487/7da42c6e-7d6b-11e5-9a02-1ad95d30fb1b.png)

Chrome has a built-in HSTS manager too, enter  **chrome://net-internals/#hsts**

**Comment by palant** [comment]
Sorry, that's out of scope for Enforce Encryption - it's a very simple extension, not meant to become a Swiss army knife. I used to link to Force TLS for "more features," too bad that it became unsupported.
